Add onBeforeChange trigger and options to item
Robophil/Product-Tour pull request #11
Opened 2017-08-22 23:10 UTC by damianfabian

I just made this features for my own use and thought you would like to check if could be merged with your current library.

1.  Added onBeforeChange trigger that would be executed before the changeStep function is being called.
2. Added options to the steps API. Now, if you define the options in one step, you will be available to define the position of the navigation for that specific step.

2017-08-23 07:41 UTC, Robophil commented
Thanks @damianfabian, I'll look at this in a bit

2017-08-23 09:24 UTC, Robophil commented
Thanks for this @damianfabian, but did you get the example running after you made your changes?
I gave it a try, clicking next no longer works.

## steps to reproduce

1. `bower install`

1. `npm install`

1. `gulpe serve`

2017-08-23 09:44 UTC, damianfabian commented
I'm using it in my Tour right now, but i'll check again with the repository flow and let you know soon.

2017-08-23 10:01 UTC, damianfabian commented
Sorry, I did not tried before with your repo, I made a little change, now should be fine for you. @Robophil

2017-08-23 10:17 UTC, Robophil commented
alright, let me give it another try

2017-08-23 14:30 UTC, Robophil commented
it works better now @damianfabian.
But when you get to the final item, and you want to navigate backward, it throws an error

```javascript
product-tour.js:183 Uncaught TypeError: Cannot read property 'element' of undefined
    at HTMLAnchorElement.<anonymous> (product-tour.js:183)
    at HTMLDivElement.dispatch (jquery.min.js:3)
    at HTMLDivElement.q.handle (jquery.min.js:3)
```

2017-08-23 14:31 UTC, robophil requested changes

2017-08-23 14:31 UTC, Robophil commented on js/product-tour.js
> +                options.onBeforeChange(jQuery(global_items[getActiveStepCount()+1].element)) ||
This line would throw an error when you get to the last ltem

2017-08-24 03:33 UTC, damianfabian commented on js/product-tour.js
> +                options.onBeforeChange(jQuery(global_items[getActiveStepCount()+1].element)) ||
Yeah, I will try to save a time to fixed maybe later today.

2018-01-31 10:12 UTC, Robophil commented
Feel free to open this up again @damianfabian when you have time to fix this. Cheers!!

2018-01-31 10:12 UTC, closed without merging